### ISSUE TITLE
Evaluation configuration steps are not found...

### ISSUE THREAD

**Issue by zhimin-z** [OpenM3D/M3DBench#2]
I have checked the readme page of this repo but found the evaluation & training configuration steps are both missing:
![image](https://github.com/OpenM3D/M3DBench/assets/8592144/130f4f91-bac9-4dd3-9b6c-d2cb94554c50)

**Comment by MSheng-Lee** [comment]
Thanks for your interest in our work! We are currently in the process of organizing the data and code to ensure they are clear, understandable, and easy to use. We will gradually upload the data, codes, and training/evaluation scripts. We appreciate your patience and understanding.

**Comment by zhimin-z** [comment]
Closed since they are added already :)
<img width="667" alt="image" src="https://github.com/user-attachments/assets/a7f3431e-b5a9-4641-b634-331a2e65e2ee">
